id: P008007
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6931
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  volumes:
    f1f50c1394434347b65f409eb9175a21:
      image_group_id: I3CN6933
      title: ''
      volume_number: 1
      total_pages: 214
ebook_metadata:
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  sku: P008007
  cover: cover.jpg
  layers:
  - pagination
