id: P008007
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6931
  title: མཆིམས་ཀྱི་རུས་རྒྱུད་སྐོར་བརྗོད་པ།
  author: ''
  volumes:
    9589286b084e4061b758549747afd3b3:
      image_group_id: I3CN6933
      title: Volume 1 of bod kyi gna' rabs mchims kyi rus rgyud skor brjod pa/
      volume_number: 1
      total_pages: 214
      base_file: v001.txt
